version: "3.3"
services:
  clientes-geral:
    container_name: "clientes-geral"
    image: 23320488/clientes-geral:latest
    restart: always
    ports:
        - 80:8080
  redis: 
    container_name: "redis"
    image: redis:alpine
    ports:
      - 6379:6379