version: "3.3"
services:
  mysql-standalone: 
    container_name: "mysql"
    image: "mysql:5.7"
    environment:
      - MYSQL_DATABASE="clientes"
      - MYSQL_USER="root"
      - MYSQL_ROOT_PASSWORD="root"
      - MYSQL_PASSWORD="root"
    ports:
      - 3307:3306
  clientes-geral:
    container_name: "clientes-geral"
    image: clientes-geral:latest
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
        - 8080:8080
    depends_on:
      - mysql-standalone
  redis: 
    container_name: "redis"
    image: redis:alpine
    ports:
      - 6379:6379